
title:              '@link-alex'
author:             Alex Manzhula
email:              manzhula.alex@gmail.com
construction_year:  2017

permalink:          pretty
baseurl:            /
url:                "http://alexmanzhula.info"

social_media:
  - link: https://www.linkedin.com/in/aliaksandr-manzhula-a8338786
    img: linkedin.png
  - link: https://github.com/link-alex
    img: github.png
  - link: https://facebook.com/a.manzhula
    img: facebook.png
  - link: mailto:manzhula.alex@gmail.com
    img: gmail.png


# Build settings
markdown:           kramdown
theme:              minima

gems:
                    - jekyll-feed
exclude:
                    - Gemfile
                    - Gemfile.lock
