
title:              '@alexmanzhula'
email:              manzhula.alex@gmail.com

description:        Some.. coding stuff?

permalink:          pretty
baseurl:            /
url:                "http://alexmanzhula.info"

twitter_username:   link__alex
github_username:    link-alex



# Build settings
markdown:           kramdown
theme:              minima

gems:
                    - jekyll-feed
exclude:
                    - Gemfile
                    - Gemfile.lock
