
title:              '@alexmanzhula'
author:             Alex Manzhula
email:              manzhula.alex@gmail.com

permalink:          pretty
baseurl:            /
url:                "http://alexmanzhula.info"

social_media:
  - link: https://www.linkedin.com/in/aliaksandr-manzhula-a8338786
    img: linkedin32.png
  - link: https://github.com/link-alex
    img: github32.png
  - link: https://twitter.com/link__alex
    img: twitter32.png
  - link: mailto::manzhula.alex@gmail.com
    img: gmail32.png


# Build settings
markdown:           kramdown
theme:              minima

gems:
                    - jekyll-feed
exclude:
                    - Gemfile
                    - Gemfile.lock
