
title:              '@alexmanzhula'
email:              manzhula.alex@gmail.com

description:        Some.. coding stuff?

permalink:          pretty
baseurl:            /
url:                "http://alexmanzhula.info"

social_media:
  - username: link-alex
    link: https://github.com/link-alex
    img: github.png
  - username: link__alex
    link: https://twitter.com/link__alex
    img: twitter.png
  - username: alex manzhula
    link: https://www.linkedin.com/in/aliaksandr-manzhula-a8338786
    img: linkedin.png


# Build settings
markdown:           kramdown
theme:              minima

gems:
                    - jekyll-feed
exclude:
                    - Gemfile
                    - Gemfile.lock
